---
version: "3"
services:
  insult-server:
    build: insult-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
    - "8080:8080"
  principals-server:
    build: principals-server
  actions-server:
    build: actions-server
  adjectives-server:
    build: adjectives-server
...
